version: '3'

networks:
  apps_network:
    external: true

services:
  mariadb:
    image: mariadb
    command: --skip-innodb-read-only-compressed
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=localapp
    networks:
      - apps_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=localapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql

#::END::
