version: "3.2"
services:
  web:
    image: gitea/gitea
    volumes:
      - type: bind
        source: ${GITEA_LOCAL_PERSISTENT_VOL}
        target: /data
    ports:
      - target: 3000
        published: ${GITEA_SERVER_HTTP_PORT}
      - target: 22
        published: ${GITEA_SERVER_SSH_PORT}
    environment:
      - MAILER_ENABLED=${GITEA_MAILER_ENABLED}
      - MAILER_HOST=${GITEA_MAILER_HOST}
      - MAILER_FROM=${GITEA_MAILER_FROM}
      - MAILER_USER=${GITEA_MAILER_USER}
      - MAILER_PASSWD=${GITEA_MAILER_PASSWORD}
    depends_on:
        - db
    restart: always
  db:
    image: bitnami/mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - type: bind
        source: ${MARIADB_LOCAL_PERSISTENT_VOL}
        target: /var/lib/mysql
    ports:
      - target: 3306
        published: ${MARIADB_SERVER_PORT}
    expose: 
      - 3306

#::END::
