version: "3.2"
services:
  keycloak:
    image: jboss/keycloak:${IMAGE_TAG}
    hostname: ${SERVER_HOST_NAME}
    ports:
      - published: ${SERVER_HOST_PORT}
        target: 8080
    environment:
      - KEYCLOAK_USER=${ADMIN_USER}
      - KEYCLOAK_PASSWORD=${ADMIN_PASSWORD}
