version: "3.2"
services:
  mongo:
    image: mongo
    hostname: ${MONGODB_HOST_NAME}
    ports:
      - published: ${MONGODB_HOST_PORT:-27017}
        target: 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD:-mongo}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - published: ${MONGO_EXPRESS_PORT:-8081}
        target: 8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMIN_USERNAME:-mongo}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_ADMIN_PASSWORD:-mongo}
